### ISSUE TITLE
cherry mx switches are too loud

### ISSUE THREAD

**Issue by rcullito** [rcullito/postmarkMitt#1]
you got it.

**Comment by commiteth** [comment]
Balance: 0.020000 ETH
Contract address: [0x538da05e4a36544325efba0aa247badfdc676787](https://ropsten.etherscan.io/address/0x538da05e4a36544325efba0aa247badfdc676787)
Network: Testnet (Ropsten)
Status: Pending maintainer confirmation
Winner: rcullito
Visit [https://rob-open-bounty.ngrok.io](https://rob-open-bounty.ngrok.io) to learn more.
