### ISSUE TITLE
dwelltime

### ISSUE THREAD

**Issue by rcullito** [rcullito/postmarkMitt#15]
a nice coffee shop in the area

**Comment by commiteth** [comment]
Balance: 0.030000 ETH
Contract address: [0xdc9a804489a55001e66f16fe34da32848df99582](https://ropsten.etherscan.io/address/0xdc9a804489a55001e66f16fe34da32848df99582)
Network: Testnet (Ropsten)
Paid to: rcullito
Visit [https://rob-open-bounty.ngrok.io](https://rob-open-bounty.ngrok.io) to learn more.
