### ISSUE TITLE
blue state

### ISSUE THREAD

**Issue by rcullito** [rcullito/postmarkMitt#16]

**Comment by commiteth** [comment]
Balance: 0.045000 ETH
Contract address: [0x0d4e85dfcda02a2f20c8c4140818daa91e9679f9](https://ropsten.etherscan.io/address/0x0d4e85dfcda02a2f20c8c4140818daa91e9679f9)
Network: Testnet (Ropsten)
Paid to: rcullito
Visit [https://rob-open-bounty.ngrok.io](https://rob-open-bounty.ngrok.io) to learn more.
