### ISSUE TITLE
rhinebeck

### ISSUE THREAD

**Issue by rcullito** [rcullito/postmarkMitt#18]
near the water

**Comment by commiteth** [comment]
Balance: 0.060000 ETH
Contract address: [0xc164db1bbefed77a705aab5380bac67ea9f29464](https://ropsten.etherscan.io/address/0xc164db1bbefed77a705aab5380bac67ea9f29464)
Network: Testnet (Ropsten)
Paid to: rcullito
Visit [https://rob-open-bounty.ngrok.io](https://rob-open-bounty.ngrok.io) to learn more.
