### ISSUE TITLE
shearwater

### ISSUE THREAD

**Issue by rcullito** [rcullito/postmarkMitt#20]

**Comment by commiteth** [comment]
Balance: 0.040000 ETH
Contract address: [0xd3fb120ad222ace7eecde188ad3d2c5a3bf0cbee](https://ropsten.etherscan.io/address/0xd3fb120ad222ace7eecde188ad3d2c5a3bf0cbee)
Network: Testnet (Ropsten)
Paid to: rcullito
Visit [https://rob-open-bounty.ngrok.io](https://rob-open-bounty.ngrok.io) to learn more.
