### ISSUE TITLE
the firmament

### ISSUE THREAD

**Issue by rcullito** [rcullito/postmarkMitt#23]

**Comment by commiteth** [comment]
Balance: 0.080800 ETH
Contract address: [0x72e8787960e4305c1b4d1852a579d63198cf2444](https://ropsten.etherscan.io/address/0x72e8787960e4305c1b4d1852a579d63198cf2444)
Network: Testnet (Ropsten)
Paid to: rcullito
Visit [https://rob-open-bounty.ngrok.io](https://rob-open-bounty.ngrok.io) to learn more.
