### ISSUE TITLE
smedley

### ISSUE THREAD

**Issue by rcullito** [rcullito/postmarkMitt#26]

**Comment by commiteth** [comment]
Balance: 0.030000 ETH
Contract address: [0x71559b0c692e270b2604c13fa920071591599fd8](https://ropsten.etherscan.io/address/0x71559b0c692e270b2604c13fa920071591599fd8)
Network: Testnet (Ropsten)
Paid to: rcullito
Visit [https://rob-open-bounty.ngrok.io](https://rob-open-bounty.ngrok.io) to learn more.
