### ISSUE TITLE
meadowbrook

### ISSUE THREAD

**Issue by rcullito** [rcullito/postmarkMitt#28]

**Comment by commiteth** [comment]
Balance: 0.070000 ETH
Contract address: [0x89ada3e01c8feeb73cc801a724b618ad76d978ca](https://ropsten.etherscan.io/address/0x89ada3e01c8feeb73cc801a724b618ad76d978ca)
Network: Testnet (Ropsten)
Paid to: rcullito
Visit [https://rob-open-bounty.ngrok.io](https://rob-open-bounty.ngrok.io) to learn more.
