### ISSUE TITLE
something is up 

### ISSUE THREAD

**Issue by rcullito** [rcullito/postmarkMitt#3]

**Comment by commiteth** [comment]
![Contract deploying](https://rob-open-bounty.ngrok.io/img/deploying_contract.png)
Transaction: [0xd1dae9fe7b1ba2b6a1fcb717282f87a02e12482154d4c4a2c4e5a76e37adad93](https://ropsten.etherscan.io/tx/0xd1dae9fe7b1ba2b6a1fcb717282f87a02e12482154d4c4a2c4e5a76e37adad93)
