### ISSUE TITLE
blah

### ISSUE THREAD

**Issue by rcullito** [rcullito/postmarkMitt#30]

**Comment by commiteth** [comment]
Balance: 0.120000 ETH
Contract address: [0xc92d49087e42942aabd80fe3df68b83f914bde3b](https://ropsten.etherscan.io/address/0xc92d49087e42942aabd80fe3df68b83f914bde3b)
Network: Testnet (Ropsten)
Paid to: rcullito
Visit [https://rob-open-bounty.ngrok.io](https://rob-open-bounty.ngrok.io) to learn more.
