### ISSUE TITLE
night

### ISSUE THREAD

**Issue by rcullito** [rcullito/postmarkMitt#31]

**Comment by commiteth** [comment]
Balance: 0.060000 ETH
Contract address: [0xaf483c73597fdd0d00c70a98d11b00d6f261f9c8](https://ropsten.etherscan.io/address/0xaf483c73597fdd0d00c70a98d11b00d6f261f9c8)
Network: Testnet (Ropsten)
Paid to: rcullito
Visit [https://rob-open-bounty.ngrok.io](https://rob-open-bounty.ngrok.io) to learn more.
