### ISSUE TITLE
dawn

### ISSUE THREAD

**Issue by rcullito** [rcullito/postmarkMitt#32]

**Comment by commiteth** [comment]
Balance: 0.040000 ETH
Contract address: [0x1f784373655e20b23985e9fe2de5b5730df80197](https://ropsten.etherscan.io/address/0x1f784373655e20b23985e9fe2de5b5730df80197)
Network: Testnet (Ropsten)
Paid to: rcullito
Visit [https://rob-open-bounty.ngrok.io](https://rob-open-bounty.ngrok.io) to learn more.
