### ISSUE TITLE
hat

### ISSUE THREAD

**Issue by rcullito** [rcullito/postmarkMitt#33]

**Comment by commiteth** [comment]
Balance: 0.080000 ETH
Contract address: [0xafccd3d951b752b04ee6997a518af51403b7b2be](https://ropsten.etherscan.io/address/0xafccd3d951b752b04ee6997a518af51403b7b2be)
Network: Testnet (Ropsten)
Paid to: rcullito
Visit [https://rob-open-bounty.ngrok.io](https://rob-open-bounty.ngrok.io) to learn more.
