### ISSUE TITLE
oblivion

### ISSUE THREAD

**Issue by rcullito** [rcullito/postmarkMitt#35]

**Comment by commiteth** [comment]
Balance: 0.060000 ETH
Contract address: [0x8230b53a34410af1cd6561ea1fdb0881ffbdf222](https://ropsten.etherscan.io/address/0x8230b53a34410af1cd6561ea1fdb0881ffbdf222)
Network: Testnet (Ropsten)
Paid to: rcullito
Visit [https://rob-open-bounty.ngrok.io](https://rob-open-bounty.ngrok.io) to learn more.
