### ISSUE TITLE
friday

### ISSUE THREAD

**Issue by rcullito** [rcullito/postmarkMitt#36]

**Comment by commiteth** [comment]
Balance: 0.020000 ETH
Contract address: [0xc8c0b0185159040b31ef45c440664c8bf3656f28](https://ropsten.etherscan.io/address/0xc8c0b0185159040b31ef45c440664c8bf3656f28)
Network: Testnet (Ropsten)
Paid to: rcullito
Visit [https://rob-open-bounty.ngrok.io](https://rob-open-bounty.ngrok.io) to learn more.
