### ISSUE TITLE
glass

### ISSUE THREAD

**Issue by rcullito** [rcullito/postmarkMitt#39]

**Comment by commiteth** [comment]
Balance: 0.080000 ETH
Contract address: [0x073ec3c437548269a77c14936ec0d40123b76b43](https://ropsten.etherscan.io/address/0x073ec3c437548269a77c14936ec0d40123b76b43)
Network: Testnet (Ropsten)
Paid to: rcullito
Visit [https://rob-open-bounty.ngrok.io](https://rob-open-bounty.ngrok.io) to learn more.
