### ISSUE TITLE
chair

### ISSUE THREAD

**Issue by rcullito** [rcullito/postmarkMitt#40]

**Comment by commiteth** [comment]
Balance: 0.060000 ETH
Contract address: [0x8c9a259073cddb41e08d6516dcc6b5b0a11e3ad2](https://ropsten.etherscan.io/address/0x8c9a259073cddb41e08d6516dcc6b5b0a11e3ad2)
Network: Testnet (Ropsten)
Paid to: rcullito
Visit [https://rob-open-bounty.ngrok.io](https://rob-open-bounty.ngrok.io) to learn more.
