### ISSUE TITLE
varick 

### ISSUE THREAD

**Issue by rcullito** [rcullito/postmarkMitt#41]

**Comment by commiteth** [comment]
Balance: 0.030000 ETH
Contract address: [0x88502a1ae6c93025e66ebaf1bd42e40ef267fd19](https://ropsten.etherscan.io/address/0x88502a1ae6c93025e66ebaf1bd42e40ef267fd19)
Network: Testnet (Ropsten)
Paid to: rcullito
Visit [https://rob-open-bounty.ngrok.io](https://rob-open-bounty.ngrok.io) to learn more.
