### ISSUE TITLE
out of water

### ISSUE THREAD

**Issue by rcullito** [rcullito/postmarkMitt#7]

**Comment by commiteth** [comment]
Balance: 0.040000 ETH
Contract address: [0xecb206147dc8122d546e5f1929c12d4351be5f36](https://ropsten.etherscan.io/address/0xecb206147dc8122d546e5f1929c12d4351be5f36)
Network: Testnet (Ropsten)
Paid to: rcullito
Visit [https://rob-open-bounty.ngrok.io](https://rob-open-bounty.ngrok.io) to learn more.
