### ISSUE TITLE
an owl is in the barn 

### ISSUE THREAD

**Issue by rcullito** [rcullito/postmarkMitt#9]

**Comment by commiteth** [comment]
Balance: 0.021000 ETH
Contract address: [0x6e96194faf574d9c126da1ad25da4e6b25efe58d](https://ropsten.etherscan.io/address/0x6e96194faf574d9c126da1ad25da4e6b25efe58d)
Network: Testnet (Ropsten)
Paid to: rcullito
Visit [https://rob-open-bounty.ngrok.io](https://rob-open-bounty.ngrok.io) to learn more.
